### ISSUE TITLE
system crashes when user doesn't select difficulty or pattern in StartPanel

### ISSUE THREAD

**Issue by yliu202** [cristal44/matchingGame#1]
If the user doesn't select difficulty or pattern and closes the pop-up message box instead, the system will still go to GamePanel but the whole screen will be pure white, shown in the following screenshot:
![Screenshot 2021-02-23 162645](https://user-images.githubusercontent.com/71121456/108916478-eede9780-75f3-11eb-8a62-de8ea12a1f3d.png)

Possible solution would be to validate the user input before switching panel, keep popping up message box if the user didn't select anything.

**Comment by cristal44** [comment]
fixed
